#!/usr/bin/env python3
"""Convert one CSV file to a deterministic, losslessly verifiable longtable."""

import argparse
import csv
import json
from pathlib import Path
import re
import sys


_COMMENT = "% Generated by tools/tab2latex.py; do not edit.\n"
_PRESENTATION_PREFIX = "% Presentation metadata: "
_BEGIN_PREFIX = r"\begin{longtable}{|"
_HLINE = "\\hline\n"
_ROW_SUFFIX = " \\\\ \\hline\n"
_ENDHEAD = "\\endhead\n"
_END = "\\end{longtable}\n"
_CELL_SEPARATOR = " & "
_CANONICAL_INTEGER = re.compile(r"(?:0|-?[1-9][0-9]*)\Z")
_DISPLAY_INTEGER = re.compile(r"(?:0|-?[1-9][0-9]{0,2}(?:,[0-9]{3})*)\Z")

_ESCAPE_MAP = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}
_INVERSE_ESCAPES = tuple(
    sorted(
        ((token, character) for character, token in _ESCAPE_MAP.items()),
        key=lambda item: len(item[0]),
        reverse=True,
    )
)


class ConversionError(ValueError):
    """Raised when input or generated output violates the canonical format."""


def _read_csv(path: Path) -> list[list[str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.reader(handle, strict=True))

    if not rows or not rows[0]:
        raise ConversionError("the CSV must contain a non-empty header row")

    width = len(rows[0])
    for row_index, row in enumerate(rows, start=1):
        if len(row) != width:
            raise ConversionError(
                f"row {row_index} has {len(row)} columns; expected {width}"
            )
        for column_index, cell in enumerate(row, start=1):
            for character in cell:
                codepoint = ord(character)
                if codepoint < 32 or codepoint == 127:
                    raise ConversionError(
                        "row "
                        f"{row_index}, column {column_index} contains unsupported "
                        f"control character U+{codepoint:04X}"
                    )
    return rows


def _escape_cell(cell: str) -> str:
    return "".join(_ESCAPE_MAP.get(character, character) for character in cell)


def _unescape_cell(cell: str) -> str:
    decoded: list[str] = []
    offset = 0
    while offset < len(cell):
        for token, character in _INVERSE_ESCAPES:
            if cell.startswith(token, offset):
                decoded.append(character)
                offset += len(token)
                break
        else:
            character = cell[offset]
            if character in _ESCAPE_MAP:
                raise ConversionError(
                    f"bare or unknown LaTeX special at cell offset {offset}"
                )
            decoded.append(character)
            offset += 1
    return "".join(decoded)


def _validate_header_map(
    source_headers: list[str], header_map: dict[str, str]
) -> None:
    if len(set(source_headers)) != len(source_headers):
        raise ConversionError("header mapping requires unique source headers")
    if set(header_map) != set(source_headers):
        missing = sorted(set(source_headers) - set(header_map))
        extra = sorted(set(header_map) - set(source_headers))
        raise ConversionError(
            f"header mapping must cover every source header; missing={missing}, extra={extra}"
        )
    display_headers = list(header_map.values())
    if any(not isinstance(value, str) or not value for value in display_headers):
        raise ConversionError("every display header must be a non-empty string")
    if len(set(display_headers)) != len(display_headers):
        raise ConversionError("display headers must be unique for a bijective mapping")


def _parse_header_map(raw_mapping: str | None) -> dict[str, str]:
    if raw_mapping is None:
        return {}
    try:
        parsed = json.loads(raw_mapping)
    except json.JSONDecodeError as error:
        raise ConversionError(f"--header-map is not valid JSON: {error}") from error
    if not isinstance(parsed, dict) or any(
        not isinstance(key, str) or not isinstance(value, str)
        for key, value in parsed.items()
    ):
        raise ConversionError("--header-map must be a JSON object of string pairs")
    return parsed


def _format_integer(cell: str) -> str:
    if not _CANONICAL_INTEGER.fullmatch(cell):
        return cell
    return f"{int(cell):,}"


def _presentation_metadata(
    source_headers: list[str], header_map: dict[str, str], thousands: bool
) -> dict:
    if header_map:
        _validate_header_map(source_headers, header_map)
    return {
        "header_map": header_map,
        "source_headers": source_headers,
        "thousands": thousands,
    }


def _metadata_comment(metadata: dict) -> str:
    encoded = json.dumps(
        metadata, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    )
    return _PRESENTATION_PREFIX + encoded + "\n"


def _present_rows(rows: list[list[str]], metadata: dict) -> list[list[str]]:
    header_map = metadata["header_map"]
    presented = [
        [header_map.get(header, header) for header in rows[0]]
    ]
    for source_row in rows[1:]:
        if metadata["thousands"]:
            presented.append([_format_integer(cell) for cell in source_row])
        else:
            presented.append(list(source_row))
    return presented


def _render(rows: list[list[str]], metadata: dict) -> str:
    width = len(rows[0])
    begin = _BEGIN_PREFIX + ("l|" * width) + "}\n"
    presented_rows = _present_rows(rows, metadata)
    encoded_rows = [
        _CELL_SEPARATOR.join(_escape_cell(cell) for cell in row)
        for row in presented_rows
    ]
    header = encoded_rows[0] + _ROW_SUFFIX + _ENDHEAD
    body = "".join(row + _ROW_SUFFIX for row in encoded_rows[1:])
    presentation_comment = (
        _metadata_comment(metadata)
        if metadata["header_map"] or metadata["thousands"]
        else ""
    )
    return _COMMENT + presentation_comment + begin + _HLINE + header + body + _END


def _decode_row(encoded_row: str, width: int) -> list[str]:
    encoded_cells = encoded_row.split(_CELL_SEPARATOR)
    if len(encoded_cells) != width:
        raise ConversionError(
            f"generated row has {len(encoded_cells)} columns; expected {width}"
        )
    return [_unescape_cell(cell) for cell in encoded_cells]


def _parse_generated(text: str) -> tuple[list[list[str]], dict]:
    if not text.startswith(_COMMENT):
        raise ConversionError("generated LaTeX has an invalid provenance comment")

    remaining = text[len(_COMMENT) :]
    first_line, newline, remaining_after_first = remaining.partition("\n")
    if not newline:
        raise ConversionError("generated LaTeX has no longtable declaration")
    metadata: dict | None = None
    if first_line.startswith(_PRESENTATION_PREFIX):
        try:
            metadata = json.loads(first_line[len(_PRESENTATION_PREFIX) :])
        except json.JSONDecodeError as error:
            raise ConversionError("generated presentation metadata is invalid") from error
        if set(metadata) != {"header_map", "source_headers", "thousands"}:
            raise ConversionError("generated presentation metadata has unexpected fields")
        if not isinstance(metadata["source_headers"], list) or any(
            not isinstance(header, str) for header in metadata["source_headers"]
        ):
            raise ConversionError("generated source-header metadata is invalid")
        if not isinstance(metadata["header_map"], dict) or any(
            not isinstance(key, str) or not isinstance(value, str)
            for key, value in metadata["header_map"].items()
        ):
            raise ConversionError("generated header-map metadata is invalid")
        if not isinstance(metadata["thousands"], bool):
            raise ConversionError("generated thousands metadata is invalid")
        if not metadata["header_map"] and not metadata["thousands"]:
            raise ConversionError(
                "presentation metadata is forbidden when no presentation option is active"
            )
        if metadata["header_map"]:
            _validate_header_map(metadata["source_headers"], metadata["header_map"])
        if first_line + "\n" != _metadata_comment(metadata):
            raise ConversionError("presentation metadata is not canonical")
        begin_line, newline, remaining = remaining_after_first.partition("\n")
        if not newline:
            raise ConversionError("generated LaTeX has no longtable declaration")
    else:
        begin_line = first_line
        remaining = remaining_after_first
    if not begin_line.startswith(_BEGIN_PREFIX) or not begin_line.endswith("}"):
        raise ConversionError("generated LaTeX has an invalid longtable declaration")

    specification = begin_line[len(_BEGIN_PREFIX) : -1]
    columns = specification.split("|")
    if (
        not specification
        or columns[-1] != ""
        or any(column != "l" for column in columns[:-1])
    ):
        raise ConversionError("generated LaTeX has an invalid column specification")
    width = len(columns) - 1

    if not remaining.startswith(_HLINE):
        raise ConversionError("generated LaTeX is missing its opening rule")
    remaining = remaining[len(_HLINE) :]

    header_marker = _ROW_SUFFIX + _ENDHEAD
    header_end = remaining.find(header_marker)
    if header_end < 0:
        raise ConversionError("generated LaTeX has no canonical header terminator")
    encoded_header = remaining[:header_end]
    remaining = remaining[header_end + len(header_marker) :]

    if not remaining.endswith(_END):
        raise ConversionError("generated LaTeX has an invalid final delimiter")
    encoded_body = remaining[: -len(_END)]

    encoded_rows = [encoded_header]
    if encoded_body:
        if not encoded_body.endswith(_ROW_SUFFIX):
            raise ConversionError("generated LaTeX has an invalid row terminator")
        encoded_rows.extend(
            encoded_body[: -len(_ROW_SUFFIX)].split(_ROW_SUFFIX)
        )

    decoded_rows = [_decode_row(row, width) for row in encoded_rows]
    if metadata is None:
        metadata = _presentation_metadata(decoded_rows[0], {}, False)
    return decoded_rows, metadata


def _restore_source_rows(presented_rows: list[list[str]], metadata: dict) -> list[list[str]]:
    if not presented_rows:
        raise ConversionError("generated LaTeX contains no rows")
    source_headers = metadata["source_headers"]
    header_map = metadata["header_map"]
    expected_header = [header_map.get(header, header) for header in source_headers]
    if presented_rows[0] != expected_header:
        raise ConversionError("display header does not match presentation metadata")

    restored = [list(source_headers)]
    for row_index, presented_row in enumerate(presented_rows[1:], start=2):
        source_row: list[str] = []
        for column_index, cell in enumerate(presented_row, start=1):
            if metadata["thousands"] and _DISPLAY_INTEGER.fullmatch(cell):
                unformatted = cell.replace(",", "")
                if not _CANONICAL_INTEGER.fullmatch(unformatted):
                    raise ConversionError(
                        f"invalid formatted integer at row {row_index}, column {column_index}"
                    )
                if _format_integer(unformatted) != cell:
                    raise ConversionError(
                        f"non-canonical thousands format at row {row_index}, column {column_index}"
                    )
                source_row.append(unformatted)
            else:
                source_row.append(cell)
        restored.append(source_row)
    return restored


def _assert_round_trip(expected: list[list[str]], generated: str) -> None:
    presented_rows, metadata = _parse_generated(generated)
    _assert_same(expected, _restore_source_rows(presented_rows, metadata))


def _assert_same(expected: list[list[str]], actual: list[list[str]]) -> None:
    if len(expected) != len(actual):
        raise ConversionError(
            f"round-trip row count differs: expected {len(expected)}, got {len(actual)}"
        )
    for row_index, (expected_row, actual_row) in enumerate(
        zip(expected, actual), start=1
    ):
        if len(expected_row) != len(actual_row):
            raise ConversionError(
                "round-trip column count differs at row "
                f"{row_index}: expected {len(expected_row)}, got {len(actual_row)}"
            )
        for column_index, (expected_cell, actual_cell) in enumerate(
            zip(expected_row, actual_row), start=1
        ):
            if expected_cell != actual_cell:
                raise ConversionError(
                    f"round-trip mismatch at row {row_index}, column {column_index}"
                )


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert one UTF-8 CSV file to a deterministic LaTeX longtable."
    )
    parser.add_argument("input_csv", type=Path, help="input UTF-8 CSV file")
    parser.add_argument("--output", required=True, type=Path, help="output .tex file")
    parser.add_argument(
        "--header-map",
        metavar="JSON",
        help="JSON object mapping every source header to a unique display label",
    )
    parser.add_argument(
        "--thousands",
        action="store_true",
        help="format canonical integer cells with thousands separators",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="reopen, parse and compare the written LaTeX with the input CSV",
    )
    return parser.parse_args()


def main() -> int:
    arguments = _parse_args()
    input_path = arguments.input_csv
    output_path = arguments.output

    try:
        if input_path.resolve() == output_path.resolve():
            raise ConversionError("input and output paths must differ")
        if (
            input_path.exists()
            and output_path.exists()
            and input_path.samefile(output_path)
        ):
            raise ConversionError("input and output paths must differ")

        rows = _read_csv(input_path)
        header_map = _parse_header_map(arguments.header_map)
        metadata = _presentation_metadata(rows[0], header_map, arguments.thousands)
        rendered = _render(rows, metadata)
        _assert_round_trip(rows, rendered)

        temporary_path = output_path.with_name(f".{output_path.name}.tmp")
        temporary_created = False
        promoted = False
        try:
            with temporary_path.open(
                "x", encoding="utf-8", newline=""
            ) as handle:
                temporary_created = True
                handle.write(rendered)

            if arguments.verify:
                with temporary_path.open(
                    "r", encoding="utf-8", newline=""
                ) as handle:
                    written = handle.read()
                _assert_round_trip(rows, written)

            temporary_path.replace(output_path)
            promoted = True
        finally:
            if temporary_created and not promoted:
                temporary_path.unlink(missing_ok=True)

        if arguments.verify:
            with output_path.open("r", encoding="utf-8", newline="") as handle:
                written = handle.read()
            _assert_round_trip(rows, written)
    except (ConversionError, OSError, UnicodeError, csv.Error) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
