#!/usr/bin/env python3
"""Convert one CSV file to a deterministic, losslessly verifiable longtable."""

import argparse
import csv
from pathlib import Path
import sys


_COMMENT = "% Generated by tools/tab2latex.py; do not edit.\n"
_BEGIN_PREFIX = r"\begin{longtable}{|"
_HLINE = "\\hline\n"
_ROW_SUFFIX = " \\\\ \\hline\n"
_ENDHEAD = "\\endhead\n"
_END = "\\end{longtable}\n"
_CELL_SEPARATOR = " & "

_ESCAPE_MAP = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}
_INVERSE_ESCAPES = tuple(
    sorted(
        ((token, character) for character, token in _ESCAPE_MAP.items()),
        key=lambda item: len(item[0]),
        reverse=True,
    )
)


class ConversionError(ValueError):
    """Raised when input or generated output violates the canonical format."""


def _read_csv(path: Path) -> list[list[str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.reader(handle, strict=True))

    if not rows or not rows[0]:
        raise ConversionError("the CSV must contain a non-empty header row")

    width = len(rows[0])
    for row_index, row in enumerate(rows, start=1):
        if len(row) != width:
            raise ConversionError(
                f"row {row_index} has {len(row)} columns; expected {width}"
            )
        for column_index, cell in enumerate(row, start=1):
            for character in cell:
                codepoint = ord(character)
                if codepoint < 32 or codepoint == 127:
                    raise ConversionError(
                        "row "
                        f"{row_index}, column {column_index} contains unsupported "
                        f"control character U+{codepoint:04X}"
                    )
    return rows


def _escape_cell(cell: str) -> str:
    return "".join(_ESCAPE_MAP.get(character, character) for character in cell)


def _unescape_cell(cell: str) -> str:
    decoded: list[str] = []
    offset = 0
    while offset < len(cell):
        for token, character in _INVERSE_ESCAPES:
            if cell.startswith(token, offset):
                decoded.append(character)
                offset += len(token)
                break
        else:
            character = cell[offset]
            if character in _ESCAPE_MAP:
                raise ConversionError(
                    f"bare or unknown LaTeX special at cell offset {offset}"
                )
            decoded.append(character)
            offset += 1
    return "".join(decoded)


def _render(rows: list[list[str]]) -> str:
    width = len(rows[0])
    begin = _BEGIN_PREFIX + ("l|" * width) + "}\n"
    encoded_rows = [
        _CELL_SEPARATOR.join(_escape_cell(cell) for cell in row) for row in rows
    ]
    header = encoded_rows[0] + _ROW_SUFFIX + _ENDHEAD
    body = "".join(row + _ROW_SUFFIX for row in encoded_rows[1:])
    return _COMMENT + begin + _HLINE + header + body + _END


def _decode_row(encoded_row: str, width: int) -> list[str]:
    encoded_cells = encoded_row.split(_CELL_SEPARATOR)
    if len(encoded_cells) != width:
        raise ConversionError(
            f"generated row has {len(encoded_cells)} columns; expected {width}"
        )
    return [_unescape_cell(cell) for cell in encoded_cells]


def _parse_generated(text: str) -> list[list[str]]:
    if not text.startswith(_COMMENT):
        raise ConversionError("generated LaTeX has an invalid provenance comment")

    remaining = text[len(_COMMENT) :]
    begin_line, newline, remaining = remaining.partition("\n")
    if not newline:
        raise ConversionError("generated LaTeX has no longtable declaration")
    if not begin_line.startswith(_BEGIN_PREFIX) or not begin_line.endswith("}"):
        raise ConversionError("generated LaTeX has an invalid longtable declaration")

    specification = begin_line[len(_BEGIN_PREFIX) : -1]
    columns = specification.split("|")
    if (
        not specification
        or columns[-1] != ""
        or any(column != "l" for column in columns[:-1])
    ):
        raise ConversionError("generated LaTeX has an invalid column specification")
    width = len(columns) - 1

    if not remaining.startswith(_HLINE):
        raise ConversionError("generated LaTeX is missing its opening rule")
    remaining = remaining[len(_HLINE) :]

    header_marker = _ROW_SUFFIX + _ENDHEAD
    header_end = remaining.find(header_marker)
    if header_end < 0:
        raise ConversionError("generated LaTeX has no canonical header terminator")
    encoded_header = remaining[:header_end]
    remaining = remaining[header_end + len(header_marker) :]

    if not remaining.endswith(_END):
        raise ConversionError("generated LaTeX has an invalid final delimiter")
    encoded_body = remaining[: -len(_END)]

    encoded_rows = [encoded_header]
    if encoded_body:
        if not encoded_body.endswith(_ROW_SUFFIX):
            raise ConversionError("generated LaTeX has an invalid row terminator")
        encoded_rows.extend(
            encoded_body[: -len(_ROW_SUFFIX)].split(_ROW_SUFFIX)
        )

    return [_decode_row(row, width) for row in encoded_rows]


def _assert_same(expected: list[list[str]], actual: list[list[str]]) -> None:
    if len(expected) != len(actual):
        raise ConversionError(
            f"round-trip row count differs: expected {len(expected)}, got {len(actual)}"
        )
    for row_index, (expected_row, actual_row) in enumerate(
        zip(expected, actual), start=1
    ):
        if len(expected_row) != len(actual_row):
            raise ConversionError(
                "round-trip column count differs at row "
                f"{row_index}: expected {len(expected_row)}, got {len(actual_row)}"
            )
        for column_index, (expected_cell, actual_cell) in enumerate(
            zip(expected_row, actual_row), start=1
        ):
            if expected_cell != actual_cell:
                raise ConversionError(
                    f"round-trip mismatch at row {row_index}, column {column_index}"
                )


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert one UTF-8 CSV file to a deterministic LaTeX longtable."
    )
    parser.add_argument("input_csv", type=Path, help="input UTF-8 CSV file")
    parser.add_argument("--output", required=True, type=Path, help="output .tex file")
    parser.add_argument(
        "--verify",
        action="store_true",
        help="reopen, parse and compare the written LaTeX with the input CSV",
    )
    return parser.parse_args()


def main() -> int:
    arguments = _parse_args()
    input_path = arguments.input_csv
    output_path = arguments.output

    try:
        if input_path.resolve() == output_path.resolve():
            raise ConversionError("input and output paths must differ")
        if (
            input_path.exists()
            and output_path.exists()
            and input_path.samefile(output_path)
        ):
            raise ConversionError("input and output paths must differ")

        rows = _read_csv(input_path)
        rendered = _render(rows)
        _assert_same(rows, _parse_generated(rendered))

        temporary_path = output_path.with_name(f".{output_path.name}.tmp")
        temporary_created = False
        promoted = False
        try:
            with temporary_path.open(
                "x", encoding="utf-8", newline=""
            ) as handle:
                temporary_created = True
                handle.write(rendered)

            if arguments.verify:
                with temporary_path.open(
                    "r", encoding="utf-8", newline=""
                ) as handle:
                    written = handle.read()
                _assert_same(rows, _parse_generated(written))

            temporary_path.replace(output_path)
            promoted = True
        finally:
            if temporary_created and not promoted:
                temporary_path.unlink(missing_ok=True)

        if arguments.verify:
            with output_path.open("r", encoding="utf-8", newline="") as handle:
                written = handle.read()
            _assert_same(rows, _parse_generated(written))
    except (ConversionError, OSError, UnicodeError, csv.Error) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
